# Generated by Django 2.1.7 on 2019-04-09 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionCargaBulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField()),
                ('numero_carga', models.CharField(max_length=20)),
                ('destino', models.IntegerField()),
                ('local', models.CharField(blank=True, max_length=45, null=True)),
                ('paradas', models.IntegerField(blank=True, null=True)),
                ('numero_lpn', models.CharField(max_length=25, unique=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('guia_remision', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('transportista', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_placa', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'planificacion_carga_bulto',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCargaMasiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planificacion_carga_masiva',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCargaPuntoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(max_length=12)),
                ('numero_lpn', models.CharField(max_length=25)),
                ('latitud', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField()),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True)),
                ('coordenadas_poligon', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planificacion_carga_punto_control',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionDetalleGeocerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'planificacion_detalle_geocerca',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionGeocerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=500, null=True)),
                ('coordenadas_poligon', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'planificacion_geocerca',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=250)),
                ('ruta', models.CharField(max_length=10)),
                ('latitud', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField()),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True)),
                ('coordenadas_poligon', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planificacion_incidencia',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionPuntoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('geocerca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionGeocerca')),
            ],
            options={
                'db_table': 'planificacion_punto_control',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionRuta',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'planificacion_ruta',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionTipoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'planificacion_tipo_control',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionTipoGeocerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcions', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'planificacion_tipo_geocerca',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionUsuarioRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_codigo', models.ForeignKey(db_column='ruta_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionRuta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planificacion_usuario_ruta',
            },
        ),
        migrations.CreateModel(
            name='TokenUsuarioDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dispositivo', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_usuario_dispositivo',
            },
        ),
        migrations.AddField(
            model_name='planificacionpuntocontrol',
            name='ruta_codigo',
            field=models.ForeignKey(db_column='ruta_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionRuta'),
        ),
        migrations.AddField(
            model_name='planificacionpuntocontrol',
            name='tipo_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionTipoControl'),
        ),
        migrations.AddField(
            model_name='planificaciongeocerca',
            name='tipo_geocerca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionTipoGeocerca'),
        ),
        migrations.AddField(
            model_name='planificaciondetallegeocerca',
            name='geocerca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.PlanificacionGeocerca'),
        ),
        migrations.AddField(
            model_name='planificacioncargabulto',
            name='ruta_codigo',
            field=models.ForeignKey(db_column='ruta_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionRuta'),
        ),
        migrations.AddField(
            model_name='planificacioncargabulto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='planificacioncargabulto',
            unique_together={('id', 'numero_lpn')},
        ),
    ]
