# Generated by Django 2.1.8 on 2019-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionpuntocontrol',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
