# Generated by Django 2.1.1 on 2019-05-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0002_planificacionpuntocontrol_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePlanificacionCargaBulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField()),
                ('numero_carga', models.CharField(max_length=20)),
                ('destino', models.IntegerField()),
                ('local', models.CharField(blank=True, max_length=45, null=True)),
                ('paradas', models.IntegerField(blank=True, null=True)),
                ('numero_lpn', models.CharField(max_length=25, unique=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('guia_remision', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('transportista', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_placa', models.CharField(blank=True, max_length=12, null=True)),
                ('ruta_codigo', models.ForeignKey(db_column='ruta_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='planificacion.PlanificacionRuta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planificacion_carga_bulto',
            },
        ),
        migrations.AlterUniqueTogether(
            name='preplanificacioncargabulto',
            unique_together={('id', 'numero_lpn')},
        ),
    ]
