# Generated by Django 2.1.1 on 2019-05-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_auto_20190526_1123'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preplanificacioncargabulto',
            table='pre_planificacion_carga_bulto',
        ),
    ]
